helm:
  charts:
    - name: postgresql
      chart_url: bitnami/postgresql
      repository_url: https://charts.bitnami.com/bitnami
      display_name: PostgreSQL
      logo: /images/helm/postgresql.webp
      template:
        - name: Storage
          key: primary.persistence.size
          type: size
          default: 10Gi
          required: true
    - name: redis
      chart_url: bitnami/redis
      repository_url: https://charts.bitnami.com/bitnami
      display_name: Redis
      logo: /images/helm/redis.webp
      template:
        - name: Storage
          key: master.persistence.size
          type: size
          default: 2Gi
          required: true
        - name: Replicas
          key: replica.replicaCount
          type: integer
          default: 0
          hidden: true
    - name: openclaw
      logo: /images/helm/openclaw.webp
      chart_url: easy-openclaw/openclaw
      repository_url: https://caninehq.github.io/openclaw-helm
      display_name: OpenClaw
    - name: metabase
      chart_url: pmint93/metabase
      repository_url: https://pmint93.github.io/helm-charts
      display_name: Metabase
      logo: /images/helm/metabase.webp
      template:
        - name: Connection URI
          key: database.connectionURI
          type: string
          required: true
        - name: Database type
          key: database.type
          type: enum
          options:
            - postgres
            - mysql
          required: true
    - name: elasticsearch
      logo: /images/helm/elasticsearch.webp
      chart_url: bitnami/elasticsearch
      repository_url: https://charts.bitnami.com/bitnami
      display_name: Elasticsearch
      template:
        - name: Storage size
          key: resources.limits.storage
          type: size
          default: 10Gi

    - name: clickhouse
      logo: /images/helm/clickhouse.webp
      chart_url: bitnami/clickhouse
      repository_url: https://charts.bitnami.com/bitnami
      display_name: ClickHouse
      template:
        - name: Storage Size
          key: persistence.size
          type: size
          default: 10Gi
        - name: Shards
          key: shards
          type: integer
          default: 1
        - name: Replicas
          key: replicaCount
          type: integer
          default: 1
        - name: "Zookeeper enabled"
          key: zookeeper.enabled
          type: boolean
          default: false
        - name: "Zookeeper replica count"
          key: zookeeper.replicaCount
          type: integer
          default: 1

    - name: airbyte
      display_name: Airbyte
      logo: /images/helm/airbyte.webp
      chart_url: airbyte/airbyte
      repository_url: https://airbytehq.github.io/helm-charts

    - name: prometheus
      logo: /images/helm/prometheus.webp
      chart_url: prometheus-community/prometheus
      repository_url: https://prometheus-community.github.io/helm-charts

    - name: portainer
      logo: /images/helm/portainer.webp
      chart_url: portainer/portainer
      repository_url: https://portainer.github.io/k8s/